version: "2"
services:
  zookeeper:
    image: gog/zookeeper
    ports:
      - "2181:2181"
  kafka0:
    image: gog/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/usr/gog/kafka/config/kafka_server_jaas.conf"
    depends_on:
      - "zookeeper"
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka0:9093"
      KAFKA_PROPERTIES_FILE: "/usr/gog/kafka.properties"
    volumes:
      - ./kafka.properties:/usr/gog/kafka.properties
    depends_on:
      - "kafka0"